[package]
name = "hasp-backend-op"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
description = "op:// backend for hasp — 1Password CLI subprocess wrapper."

[dependencies]
hasp-core = { path = "../hasp-core" }
url = "2.5"
secrecy = "0.10"
serde_json = { workspace = true }

[dev-dependencies]
hasp-core = { path = "../hasp-core", features = ["test-utils"] }
